urls.py
# urls.py
from django.conf.urls import url
from otree.urls import urlpatterns
from IPScrabble.pages import dictionary


urlpatterns.append(url(r'^dictionary/$', dictionary))

words_task/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random


author = 'Your name here'

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'words_task'
    players_per_group = None
    num_rounds = 1

    letter_values = {"A": 1,
                     "B": 3,
                     "C": 3,
                     "D": 2,
                     "E": 1,
                     "F": 4,
                     "G": 2,
                     "H": 4,
                     "I": 1,
                     "J": 8,
                     "K": 10,
                     "L": 1,
                     "M": 2,
                     "N": 1,
                     "O": 1,
                     "P": 3,
                     "Q": 8,
                     "R": 1,
                     "S": 1,
                     "T": 1,
                     "U": 1,
                     "V": 4,
                     "W": 10,
                     "X": 10,
                     "Y": 10,
                     "Z": 10}
    
    frequency = ['A'] * 9 + ['B'] * 2 + ['C'] * 2 + ['D'] * 3 + ['E'] * 15 + ['F'] * 2 + ['G'] * 2 + ['H'] * 2 + ['I'] * 8 + ['J'] * 1 + ['K'] * 1 + ['L'] * 5 + ['M'] * 3 + ['N'] * 6 + ['O'] * 6 + ['P'] * 2 + ['Q'] * 1 + ['R'] * 6 + ['S'] * 6 + ['T'] * 6 + ['U'] * 6 + ['V'] * 2 + ['W'] * 1 + ['X'] * 1 + ['Y'] * 1 +  ['Z'] * 1 

    
    initpayoff = c(0)
    letter_price = c(2)
    init_nb_letters = 5
    min_nb_letters = 3
    test_min_nb_letters = 3
    max_nb_letters = 5
    ext_nb_letters = 1
    test_hand = ['A','M','A','D','I','T','E','R','S']
    
    test_timeout = 180


class Subsession(BaseSubsession):
    pass

class Group(BaseGroup):
    pass      
    
class Player(BasePlayer):    
    test_words = models.LongStringField()

words_task/templates/words_task/Instructions.html
{% extends "global/Page.html" %}
{% load otree %}
{% block styles %}

<link rel="stylesheet" type="text/css" href="{% static 'global/matrix.css' %}"/>

{% endblock %}


{% block title %}
Merci, veuillez attendre à présent les instructions de l'expérimentateur.
{% endblock %}

{% block content %}

<div class="card bg-light instructions">
    <div class="card-body">

    <h3>
         Merci de suivre attentivement les consignes expliquées par l'expérimentateur.
    </h3>

    
    

</div>
</div>
{% endblock %}

words_task/templates/words_task/Test.html
{% extends "global/Page.html" %}
{% load otree %}

{% block styles %}
   <link href="{% static 'words_task/style.css' %}" rel="stylesheet">

<style>

.game {

     margin-top:0;
}
 
</style>
 

{% endblock %}
 

{% block title %}
Vous devez créer le plus de mots possible en {{test_timeout}} minutes. À vous de jouer !
{% endblock %}

{% block content %}

<div class="game">  




<div class="title_desc">Votre liste de mots</div>

<div>
  

   <div id="word_list" class="word_box">  

 

     </div>
   
 </div>
 </div>

<div class="fixed_box">
<div id="notexist" class="alert alert-danger" role="alert">Le mot n'existe pas !</div>
<div id="not_new" class="alert alert-warning" role="alert">Ce mot a déjà été créé !</div>
<div id="not_new_and_wrong" class="alert alert-danger" role="alert">Ce mot n'existe pas et vous l'avez déjà essayé !</div>

    <div class="new_box">
            <div class="title_desc" style="float: unset;">Créer un nouveau mot ({{Constants.test_min_nb_letters}} lettres min)</div>
             <div>              
               
                
            </div>
             <ul id="new_word_area" class="words" >
            </ul>
        
        
     </div>

    <div class="hand_box">  

            <div class="title_desc">Votre main</div>
    
            <ul id="hand_area" class="words">
            
            
            </ul>
    
    </div>






</div>

  
<textarea name="test_words" id="id_test_words"  style="display:none;">
</textarea>

    
{% endblock %}

{% block scripts %}
<script src="{% static 'words_task/jquery-ui.min.js' %}"></script>
<script src="{% static 'words_task/script.js' %}"></script>

  <script>

    var hand = {{test_hand|json}};


 

$( document ).ready(function() {
        
    var word = [];
    var word_list = [];
    var wrong_word_list = [];
   
    function update_hand(){ 
            hand = {{test_hand|json}};
            $( "#hand_area" ).html('');
            for(var i=0; i < hand.length ; i++){

            $( "#hand_area" ).append('<li class="ui-state-highlight sortable" value="'+hand[i]+'">'+hand[i]+'</li>');
        
            }
    }
   
    
function checkdictionary(word,csrf_token) { 
        
                                   $.ajax({
                                   type: "POST",
                                   url: "/dictionary/",
                                   traditional: true,
                                   data: {
                                           'word': word,
                                           csrfmiddlewaretoken: csrf_token,
                                         },
                                   success: function(data) {
                                          if (data=="True")
                                               {                                console.log("true");
                        
                                                }else
                                                
                                               {
                                                       console.log("false");
                                                 $("#list-"+word+" " ).addClass("notindict");
                                                 $( "#list-"+word+" " ).hide("slide", { direction: "left" }, 300);
                                                $( "#notexist" ).show();
                                                wrong_word_list.push(word);

                                                setTimeout(function(){ $( "#notexist" ).hide(); }, 1000);

                                              }
                                                    
                                                    }
                                 
                                });
}
            
   update_hand();
    $( document ).keydown(function(event) {

            if (event.key === "Backspace"){
                    $( "#new_word_area li:last" ).detach().appendTo( "#hand_area" );
                    var letter_deleted = word.pop();
                    if (letter_deleted)
                    {
                    hand.push(letter_deleted);
                    }

                    event.preventDefault();

             }else if( event.key === "Enter" && $( "#new_word_area li").length >= {{Constants.test_min_nb_letters}} ){
                    
                     word_str = word.toString().replace(new RegExp(',', 'g'), '');
console.log(word_str);
                     if(word_list.indexOf(word_str) != -1){
                        if(wrong_word_list.indexOf(word_str)!= -1 )
                        {
                           $( "#not_new_and_wrong" ).show();   
                          $( "#not_new" ).hide();  

                                }else{
                          $( "#not_new" ).show();
                          $( "#not_new_and_wrong" ).hide();  
                                        }
                     $( "#new_word_area li" ).remove();
                      word = [];
                     $( "#word_list" ).prepend('<span id="duplicated-'+word_str+'" class="test_word">'+word_str+'</span>');
                     $( "#duplicated-"+word_str+"").hide("slide", { direction: "left" }, 300);
                       update_hand(); 
                       
                         event.preventDefault();
                             }else{
                                     
                     $( "#not_new_and_wrong" ).hide();       
                
                     $( "#not_new" ).hide();

                    $( "#new_word_area li" ).remove();
                    word = [];
                     $( "#word_list" ).prepend('<span id="list-'+word_str+'" class="test_word">'+word_str+'</span>');
                    
                    $('#id_test_words').val($('#id_test_words').val()+word_str+',');
                    word_list.push(word_str);
                    
                    checkdictionary(word_str,"{{ csrf_token }}");
                    update_hand();
                    }

                    event.preventDefault();
 
                }
                else{
                            
                        
                    var letter = String.fromCharCode(event.which).toUpperCase() ;
                                         
                    
                    var hand_index = hand.indexOf(letter);
                    
                    if(hand_index != -1){
                                
                            $( "#hand_area li[value*='"+letter+"']:first" ).detach().appendTo( "#new_word_area" );
                    word.push(letter);
                    hand.splice(hand_index,1);
                        event.preventDefault();
                    }else{
                        event.preventDefault();
                    }
            
            }

    });
          
});
  </script>
{% endblock %}